<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EcoFlowMonitor.Platform.Linux</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EcoFlowMonitor.Core\EcoFlowMonitor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Linux.Bluetooth" Version="5.67.1" />
  </ItemGroup>
</Project>
