<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EcoFlowMonitor.Platform.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EcoFlowMonitor.Core\EcoFlowMonitor.Core.csproj" />
  </ItemGroup>
</Project>
